In [1]:
import pandas as pd
result=pd.read_csv('idkgrade.csv')

In [2]:
def nominalToNumber(dataframe,column,mapping):
    dataframe[column] = dataframe[column].map(mapping)
    return dataframe

def encodeData(studentData):
    registerno={
'IDK16IT001-ABHINANDHA  P':65,
'IDK16IT002-AHMED BAHEEJ K':66,
'IDK16IT003-AISWARYA  K.P':67,
'IDK16IT004-AJMAL  ':68,
'IDK16IT006-AKHIL  VINOD':69,
'IDK16IT007-ANANTHU  K':70,
'IDK16IT008-ANJALI  K P':71,
'IDK16IT010-ANWAR  FAROOQ':72,
'IDK16IT011-ARUN  G':73,
'IDK16IT012-ASHETHA  K':74,
'IDK16IT013-ASHRITH  MV':75,
'IDK16IT014-ASMIDA  NHARAKODAN':76,
'IDK16IT015-ASWINI  K D':77,
'IDK16IT016-ATHIRA  ARAVIND':78,
'IDK16IT017-ATUL MADHUSUDHANA PANICKER':79,
'IDK16IT019-DILIGENT ORATER LEE':80,
'IDK16IT020-ELSE PAUL ISAC':81,
'IDK16IT021-GOKUL  BABU':82,
'IDK16IT022-JEFFY  JAMES':83,
'IDK16IT023-JIJINA  THOMAS':84,
'IDK16IT025-LEKSHMI  C D':85,
'IDK16IT027-MANEESHA  M R':86,
'IDK16IT029-MEHNAS  P.B':87,
'IDK16IT030-MELBIN  C M':88,
'IDK16IT031-MINU  MUMTHAS K':89,
'IDK16IT034-MOHAMMED RAMZAN K':90,
'IDK16IT035-MOHAMMED SHAMEEM P V':91,
'IDK16IT037-NIMITHA  J':92,
'IDK16IT038-NIVEDITHA  T.P':93,
'IDK16IT039-NURANNEESA  K':94,
'IDK16IT040-PARVATHY  KS':95,
'IDK16IT043-RAHUL  R':96,
'IDK16IT044-SANA  V H':97,
'IDK16IT045-SHARATH  A':98,
'IDK16IT046-SILPA  K S':99,
'IDK16IT047-SILPA MOL P S':100,
'IDK16IT048-SILPA  VINOD':101,
'IDK16IT049-SURYAJITH  S':102,
'IDK16IT050-SWATHI  T K':103,
'IDK16IT052-VINAYA  MUKUNDAN':104,
'IDK16IT053-VINOD KRISHNAN  R.H':105,
'IDK16IT054-VISHNU  MP':106,
'IDK16IT055-VISMAYA  S':107,
'LIDK16IT056-AISHWARYA  PUSHPARAJ':108
}
    
    studentData = nominalToNumber(studentData,'Student',registerno)
    
    gradeMapping = {'O':10,'A+':9,'A':8,'B+':7,'B':6,'C':5,'P':4,'F':0,'FE':0,'AB':0}
    studentData = nominalToNumber(studentData,'IT401',gradeMapping)
    studentData = nominalToNumber(studentData,'IT403',gradeMapping)
    studentData = nominalToNumber(studentData,'IT405',gradeMapping)
    studentData = nominalToNumber(studentData,'IT407',gradeMapping)
    studentData = nominalToNumber(studentData,'IT409',gradeMapping)
    studentData = nominalToNumber(studentData,'IT465',gradeMapping)
    studentData = nominalToNumber(studentData,'IT451',gradeMapping)
    studentData = nominalToNumber(studentData,'IT431',gradeMapping)
    studentData = nominalToNumber(studentData,'CS467',gradeMapping)
    return studentData

In [3]:
encodeData(result)

    Student  IT401  IT403  IT405  IT407  IT409  IT465  IT451  IT431  CS467
0        65      0      6      6      5      0    5.0      9      9    NaN
1        66      6      7      9      6      6    7.0      8     10    NaN
2        67      6      9      7      7      7    5.0      9      9    NaN
3        68      5      7      6      5      5    0.0      8      7    NaN
4        69      0      0      4      0      0    0.0      8      7    NaN
5        70      0      6      5      0      0    6.0      7      7    NaN
6        71      7     10     10      7      9    6.0      9      7    NaN
7        72      5      7      6      6      6    NaN      8      8    6.0
8        73      0      7      7      5      5    6.0     10      8    NaN
9        74      6      9     10      8      8    NaN      9      7   10.0
10       75      0      6      0      0      0    0.0      9      7    NaN
11       76      6     10     10      9      9    NaN     10      9    8.0
12       77      0      7      6      5      5    5.0      8      9    NaN
13       78      6      7      7      7      5    6.0      8      8    NaN
14       79      0      0      0      0      0    0.0      0      7    NaN
15       80      0      5      0      0      4    5.0      8      7    NaN
16       81      0      5      0      0      0    0.0      0      7    NaN
17       82      5      8      6      6      7    6.0      9      7    NaN
18       83      6      7      6      6      7    NaN      9      8    7.0
19       84      6      7      6      7      6    NaN      9      7    8.0
20       85      0      9      5      5      5    5.0      8      8    NaN
21       86      6      7      7      6      8    NaN      8      7    8.0
22       87      6      9      7      7      8    7.0      9      9    NaN
23       88      5      6      4      0      0    5.0      8      7    NaN
24       89      6      7      6      7      7    NaN      9     10    7.0
25       90      5      7      5      5      5    NaN      9      7    7.0
26       91      6      7      5      5      5    5.0      8      7    NaN
27       92      6      7      6      5      5    6.0      8      7    NaN
28       93      5      8      7      7      7    6.0      9      7    NaN
29       94      5      7      7      6      7    6.0      8      8    NaN
30       95      6      8      7      7      7    NaN      9      7    9.0
31       96      6      8      5      7      6    7.0      8      7    NaN
32       97      7      9      9     10      8    NaN      9      9   10.0
33       98      5      6      5      5      5    7.0      8      7    NaN
34       99      6      6      5      5      5    5.0      9      7    NaN
35      101      6      8      6      8      7    5.0      8      9    NaN
36      102      0      9      5      7      5    6.0      7      7    NaN
37      103      6      8      7      6      7    7.0      8      7    NaN
38      104      5      8      7      5      5    6.0      8      7    NaN
39      105      4      6      0      0      0    5.0      8      7    NaN
40      106      6      6      6      7      0    NaN      9      7    7.0
41      107      0      6      5      5      0    5.0      7      7    NaN
42      108      0      6      5      5      5    5.0      8      7    NaN

In [4]:
result.to_csv(r'idk_S7.csv', index = False, header=True)