In [1]:
import pandas as pd
result=pd.read_csv('idkgrade.csv')

In [2]:
def nominalToNumber(dataframe,column,mapping):
    dataframe[column] = dataframe[column].map(mapping)
    return dataframe

def encodeData(studentData):
    registerno={
'IDK16IT001-ABHINANDHA  P':65,
'IDK16IT002-AHMED BAHEEJ K':66,
'IDK16IT003-AISWARYA  K.P':67,
'IDK16IT004-AJMAL  ':68,
'IDK16IT006-AKHIL  VINOD':69,
'IDK16IT007-ANANTHU  K':70,
'IDK16IT008-ANJALI  K P':71,
'IDK16IT010-ANWAR  FAROOQ':72,
'IDK16IT011-ARUN  G':73,
'IDK16IT012-ASHETHA  K':74,
'IDK16IT013-ASHRITH  MV':75,
'IDK16IT014-ASMIDA  NHARAKODAN':76,
'IDK16IT015-ASWINI  K D':77,
'IDK16IT016-ATHIRA  ARAVIND':78,
'IDK16IT017-ATUL MADHUSUDHANA PANICKER':79,
'IDK16IT019-DILIGENT ORATER LEE':80,
'IDK16IT020-ELSE PAUL ISAC':81,
'IDK16IT021-GOKUL  BABU':82,
'IDK16IT022-JEFFY  JAMES':83,
'IDK16IT023-JIJINA  THOMAS':84,
'IDK16IT025-LEKSHMI  C D':85,
'IDK16IT027-MANEESHA  M R':86,
'IDK16IT029-MEHNAS  P.B':87,
'IDK16IT030-MELBIN  C M':88,
'IDK16IT031-MINU  MUMTHAS K':89,
'IDK16IT034-MOHAMMED RAMZAN K':90,
'IDK16IT035-MOHAMMED SHAMEEM P V':91,
'IDK16IT037-NIMITHA  J':92,
'IDK16IT038-NIVEDITHA  T.P':93,
'IDK16IT039-NURANNEESA  K':94,
'IDK16IT040-PARVATHY  KS':95,
'IDK16IT043-RAHUL  R':96,
'IDK16IT044-SANA  V H':97,
'IDK16IT045-SHARATH  A':98,
'IDK16IT046-SILPA  K S':99,
'IDK16IT047-SILPA MOL P S':100,
'IDK16IT048-SILPA  VINOD':101,
'IDK16IT049-SURYAJITH  S':102,
'IDK16IT050-SWATHI  T K':103,
'IDK16IT052-VINAYA  MUKUNDAN':104,
'IDK16IT053-VINOD KRISHNAN  R.H':105,
'IDK16IT054-VISHNU  MP':106,
'IDK16IT055-VISMAYA  S':107,
'LIDK16IT056-AISHWARYA  PUSHPARAJ':108
}
    
    studentData = nominalToNumber(studentData,'Student',registerno)
    
    gradeMapping = {'O':10,'A+':9,'A':8,'B+':7,'B':6,'C':5,'P':4,'F':0,'FE':0,'AB':0}
    studentData = nominalToNumber(studentData,'MA202',gradeMapping)
    studentData = nominalToNumber(studentData,'CS202',gradeMapping)
    studentData = nominalToNumber(studentData,'IT202',gradeMapping)
    studentData = nominalToNumber(studentData,'CS208',gradeMapping)
    studentData = nominalToNumber(studentData,'IT204',gradeMapping)
    studentData = nominalToNumber(studentData,'HS200',gradeMapping)
    studentData = nominalToNumber(studentData,'IT234',gradeMapping)
    studentData = nominalToNumber(studentData,'IT232',gradeMapping)
    return studentData

In [3]:
encodeData(result)

    Student  MA202  CS202  IT202  IT204  CS208  HS200  IT232  IT234
0        65      7      6      5      6      6      7      8      5
1        66      7      6      6      8      7      8     10      8
2        67      7      6      6      6      6      6      9      6
3        68      4      5      5      6      5      5      8      5
4        69      0      5      0      6      0      0      8     10
5        70      5      0      0      5      5      5      7      7
6        71      9      7      9     10      7      9      7      9
7        72      0      0      0      6      0      6     10      8
8        73      7      5      5      8      5      6      8     10
9        74     10      6      9      9      7      8      8      7
10       75      6      0      0      0      4      5      8      7
11       76     10      8      9      9      7      7      9      8
12       77      5      5      6      5      5      6      8      6
13       78      7      5      6      7      7      7      7      6
14       79      0      0      0      5      0      5      7      9
15       80      6      0      0      0      0      5      8      8
16       81      5      0      0      0      0      5      6      7
17       82      7      7      6      6      5      6      8      8
18       83      9      5      6      8      6      8     10     10
19       84      9      5      6      6      5      7      9      8
20       85      7      6      5      7      6      5      9      8
21       86      7      5      7      9      6      5      8      8
22       87     10      7      6      7      6      7      8      8
23       88      4      5      5      5      5      5      6      6
24       89      6      5      5      5      5      6      7      7
25       90      4      4      0      5      4      5      7      7
26       91      6      4      5      5      5      6     10      7
27       92      5      4      5      5      5      6      7      5
28       93      8      6      6      7      5      6      9      7
29       94      6      5      7      6      5      7      7      7
30       95      8      7      6      7      6      6      8      9
31       96      6      5      6      6      5      7     10      8
32       97     10      8      7      8      6      8      9      8
33       98      7      4      5      6      6      6     10      9
34       99      7      6      5      7      6      5      9     10
35      101      8      5      6      5      4      5      8      7
36      102      5      6      7      6      5      6      7      8
37      103      7      5      6      7      5      7     10      8
38      104      7      5      5      6      5      6      8      7
39      105      9      5      5      5      6      5     10      7
40      106      5      4      6      6      5      5      8      7
41      107      0      0      0      5      0      5      7      6
42      108      0      5      5      6      0      4      7      6

In [4]:
result.to_csv(r'idk_S4.csv', index = False, header=True)