In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
#data=pd.read_csv('Dataset/Internal/ConsolidateOutput.csv')
data = pd.read_csv('internal50.csv')
data.head()

,NO.,ma_internals,ph100_internals,be10105_internals,be110_internals,be103_internals,ec100_internals,ph110_internals,ec110_internals,cs110_internals,...,HS300_internals,CS304_internals,IT304_internals,IT306_internals,IT364_internals,IT302_internals,IT332_internals,IT334_internals,IT352_internals,IT366_internals
0,1,25,23,35,48,36,30,43,42,37,...,31,29,26,31,25.0,28,36,44,29,NaN
1,2,41,46,47,46,40,37,48,43,49,...,42,41,36,29,NaN,41,32,43,35,33.0
2,3,47,50,47,37,46,50,48,43,48,...,46,50,46,46,NaN,50,49,48,44,50.0
3,5,31,41,42,39,42,43,47,48,43,...,46,46,48,48,48.0,48,43,48,38,NaN
4,6,45,46,40,41,41,39,46,47,49,...,42,45,42,38,39.0,46,40,46,38,NaN

In [3]:
x=data
xtrain, xtest = train_test_split(x, test_size = 0.2, random_state = 0)

In [4]:
xtrain.shape

(43, 47)

In [5]:
xtest.shape

(11, 47)

In [6]:
xtest

,NO.,ma_internals,ph100_internals,be10105_internals,be110_internals,be103_internals,ec100_internals,ph110_internals,ec110_internals,cs110_internals,...,HS300_internals,CS304_internals,IT304_internals,IT306_internals,IT364_internals,IT302_internals,IT332_internals,IT334_internals,IT352_internals,IT366_internals
53,62,27,25,38,40,35,35,39,44,40,...,29,34,27,39,24.0,36,43,37,35,NaN
33,40,38,42,41,39,38,37,48,43,45,...,39,40,36,35,NaN,38,46,39,39,37.0
48,57,45,46,42,47,41,50,48,49,45,...,47,46,50,49,49.0,46,49,43,43,NaN
26,33,45,39,47,46,40,34,43,43,45,...,46,39,45,36,39.0,43,41,48,42,NaN
11,13,33,42,46,41,39,35,47,46,41,...,42,29,28,33,NaN,37,44,46,37,31.0
2,3,47,50,47,37,46,50,48,43,48,...,46,50,46,46,NaN,50,49,48,44,50.0
32,39,45,43,42,47,40,41,46,48,44,...,36,36,42,40,NaN,40,49,42,45,36.0
42,51,26,29,38,39,39,32,44,42,37,...,28,23,24,25,23.0,25,31,41,23,NaN
45,54,39,43,43,42,46,47,48,48,48,...,42,45,45,39,36.0,30,45,47,34,NaN
30,37,45,50,48,42,44,50,49,49,44,...,43,48,48,48,NaN,48,36,43,45,44.0
4,6,45,46,40,41,41,39,46,47,49,...,42,45,42,38,39.0,46,40,46,38,NaN

In [7]:
xtrain

,NO.,ma_internals,ph100_internals,be10105_internals,be110_internals,be103_internals,ec100_internals,ph110_internals,ec110_internals,cs110_internals,...,HS300_internals,CS304_internals,IT304_internals,IT306_internals,IT364_internals,IT302_internals,IT332_internals,IT334_internals,IT352_internals,IT366_internals
10,12,36,39,35,42,38,32,46,40,45,...,34,31,27,32,28.0,35,33,40,42,NaN
28,35,32,34,38,33,42,34,44,45,44,...,41,45,44,43,NaN,43,48,42,43,48.0
22,26,48,43,46,42,44,48,47,46,48,...,50,48,49,48,50.0,50,47,47,40,NaN
31,38,37,50,45,34,39,44,48,46,45,...,39,42,44,48,44.0,37,37,41,38,NaN
38,45,46,39,46,42,39,41,47,45,48,...,40,38,34,41,35.0,31,36,37,35,NaN
37,44,46,47,45,41,37,50,48,44,44,...,44,39,45,47,46.0,43,45,42,43,NaN
7,9,31,34,35,34,38,38,47,45,46,...,37,36,34,45,NaN,39,34,41,35,43.0
14,17,46,46,50,46,47,41,48,46,49,...,46,41,47,46,NaN,50,49,47,47,43.0
27,34,23,27,38,36,38,29,46,39,47,...,36,42,38,45,NaN,45,46,40,40,36.0
35,42,46,45,43,39,43,47,48,49,45,...,46,47,43,50,NaN,50,49,42,43,49.0
49,58,33,36,36,44,38,39,46,47,40,...,42,45,35,49,NaN,37,49,40,34,43.0
18,22,44,42,45,44,38,43,44,41,46,...,41,46,45,37,NaN,48,38,44,41,43.0
51,60,36,33,40,45,39,40,47,45,43,...,31,26,28,32,28.0,39,34,38,34,NaN
34,41,23,26,38,41,38,40,48,43,42,...,32,25,26,33,26.0,25,34,37,27,NaN
15,19,43,38,40,47,38,47,44,41,45,...,43,41,49,42,43.0,44,37,48,37,NaN
5,7,46,47,48,39,45,47,47,47,48,...,43,42,45,40,NaN,45,47,44,41,42.0
29,36,32,36,38,37,39,37,45,43,44,...,35,37,38,38,NaN,37,49,42,35,36.0
16,20,42,48,50,45,47,41,43,45,49,...,38,44,47,43,NaN,43,49,47,43,43.0
46,55,37,39,46,40,41,44,48,46,47,...,39,40,45,41,NaN,43,49,43,40,44.0
20,24,26,29,40,34,40,41,46,41,48,...,41,49,49,32,36.0,46,36,39,35,NaN
52,61,31,25,42,31,35,26,44,36,41,...,29,30,26,31,NaN,28,33,30,34,26.0
8,10,24,24,38,40,41,32,41,41,47,...,34,32,36,31,NaN,32,40,46,34,30.0
13,16,44,49,50,46,44,48,48,43,45,...,43,44,43,43,NaN,49,49,47,44,42.0
25,31,33,39,37,36,38,35,43,45,39,...,42,37,35,38,45.0,44,42,43,42,NaN
17,21,30,38,38,38,36,39,47,43,47,...,44,35,41,39,34.0,37,39,46,36,NaN
40,48,40,49,38,39,37,41,47,44,40,...,29,25,26,26,24.0,26,30,40,30,NaN
43,52,41,44,42,47,45,48,48,45,47,...,45,43,47,45,44.0,50,47,47,40,NaN
1,2,41,46,47,46,40,37,48,43,49,...,42,41,36,29,NaN,41,32,43,35,33.0
12,15,48,45,48,47,49,33,47,42,47,...,43,44,45,41,NaN,50,48,44,37,42.0
41,49,29,29,44,45,37,30,44,44,48,...,37,31,43,41,26.0,32,45,43,34,NaN
24,30,41,43,38,40,38,36,46,44,46,...,42,42,39,38,41.0,48,49,47,33,NaN
6,8,25,40,37,39,37,40,48,44,47,...,45,32,39,41,33.0,35,32,42,37,NaN
23,28,27,29,38,30,36,28,42,36,41,...,24,31,24,32,23.0,29,30,39,28,NaN
36,43,43,42,40,46,40,43,48,44,44,...,46,44,46,43,43.0,43,41,42,43,NaN
21,25,27,27,42,40,41,27,42,39,43,...,42,47,42,38,NaN,46,41,44,40,37.0
19,23,36,47,50,47,44,43,48,48,48,...,44,45,44,41,43.0,44,36,46,40,NaN
9,11,43,47,45,41,50,49,48,49,47,...,48,46,49,47,48.0,49,44,42,40,NaN
39,46,26,35,38,40,37,29,48,40,42,...,41,37,42,46,29.0,29,40,40,30,NaN
50,59,26,39,40,44,36,34,45,43,44,...,39,40,40,32,NaN,44,44,41,38,35.0
3,5,31,41,42,39,42,43,47,48,43,...,46,46,48,48,48.0,48,43,48,38,NaN
0,1,25,23,35,48,36,30,43,42,37,...,31,29,26,31,25.0,28,36,44,29,NaN
47,56,50,48,45,46,40,41,48,48,47,...,32,32,39,39,31.0,43,47,41,36,NaN
44,53,46,46,49,47,48,47,48,48,47,...,41,46,40,38,NaN,48,49,46,47,49.0

In [8]:
xtrain.to_csv (r'all_train_int50.csv', index = False, header=True)
xtest.to_csv (r'all_test_int50.csv', index = False, header=True)